#!/bin/bash

# Zone file generator - generates random BIND format zone files
# Usage: ./zone-generator.sh [domain] [output_dir]
#        ./zone-generator.sh --random [count] [output_dir]

# Default values
OUTPUT_DIR="."
DOMAIN="${1:-example.com}"

# Generate random number in range
random_range() {
    local min=$1
    local max=$2
    echo $(( RANDOM % (max - min + 1) + min ))
}

# Generate random IPv4 address
random_ipv4() {
    echo "$(random_range 1 254).$(random_range 0 255).$(random_range 0 255).$(random_range 1 254)"
}

# Generate random IPv6 address
random_ipv6() {
    printf "2001:%04x:%04x:%04x:%04x:%04x:%04x:%04x" \
        $(random_range 0 65535) $(random_range 0 65535) \
        $(random_range 0 65535) $(random_range 0 65535) \
        $(random_range 0 65535) $(random_range 0 65535) \
        $(random_range 0 65535)
}

# Generate random string for hostnames
random_string() {
    local length=${1:-8}
    cat /dev/urandom | tr -dc 'a-z' | fold -w "$length" | head -n 1
}

# Generate random domain name
random_domain() {
    local tlds=("com" "net" "org" "io" "dev" "cloud" "tech" "app")
    local tld=${tlds[$(random_range 0 $((${#tlds[@]} - 1)))]}
    echo "$(random_string $(random_range 5 12)).$tld"
}

# Generate SOA record
generate_soa() {
    local domain=$1
    local serial=$(date +%Y%m%d)$(printf "%02d" $(random_range 1 99))
    local refresh=$(random_range 3600 14400)
    local retry=$(random_range 900 3600)
    local expire=$(random_range 604800 2419200)
    local minimum=$(random_range 300 3600)

    local ns_hosts=("ns1" "ns2" "dns1" "dns2" "primary" "secondary")
    local ns_host=${ns_hosts[$(random_range 0 $((${#ns_hosts[@]} - 1)))]}

    local admin_prefixes=("hostmaster" "admin" "dnsadmin" "postmaster")
    local admin=${admin_prefixes[$(random_range 0 $((${#admin_prefixes[@]} - 1)))]}

    cat << EOF
;
; Zone file for ${domain}
; Generated by zone-generator.sh on $(date)
;
\$ORIGIN ${domain}.
\$TTL $(random_range 300 3600)

@    IN    SOA    ${ns_host}.${domain}. ${admin}.${domain}. (
                    ${serial}    ; Serial
                    ${refresh}       ; Refresh
                    ${retry}        ; Retry
                    ${expire}     ; Expire
                    ${minimum} )     ; Negative Cache TTL
EOF
}

# Generate NS records (0, 1, 2, or 4)
generate_ns_records() {
    local domain=$1
    local choice=$(random_range 1 4)

    # NS naming pairs
    local ns_sets=(
        "ns1 ns2 ns3 ns4"
        "dns1 dns2 dns3 dns4"
        "primary secondary tertiary quaternary"
    )
    local set=${ns_sets[$(random_range 0 2)]}
    local ns1=$(echo $set | cut -d' ' -f1)
    local ns2=$(echo $set | cut -d' ' -f2)
    local ns3=$(echo $set | cut -d' ' -f3)
    local ns4=$(echo $set | cut -d' ' -f4)

    echo ""
    echo "; Name servers"

    case $choice in
        1) # Zero NS records
            echo "; (none)"
            ;;
        2) # One NS record
            echo "@    IN    NS    ${ns1}.${domain}."
            echo ""
            echo "; NS server addresses"
            echo "${ns1}    IN    A    $(random_ipv4)"
            ;;
        3) # Two NS records
            echo "@    IN    NS    ${ns1}.${domain}."
            echo "@    IN    NS    ${ns2}.${domain}."
            echo ""
            echo "; NS server addresses"
            echo "${ns1}    IN    A    $(random_ipv4)"
            echo "${ns2}    IN    A    $(random_ipv4)"
            ;;
        4) # Four NS records
            echo "@    IN    NS    ${ns1}.${domain}."
            echo "@    IN    NS    ${ns2}.${domain}."
            echo "@    IN    NS    ${ns3}.${domain}."
            echo "@    IN    NS    ${ns4}.${domain}."
            echo ""
            echo "; NS server addresses"
            echo "${ns1}    IN    A    $(random_ipv4)"
            echo "${ns2}    IN    A    $(random_ipv4)"
            echo "${ns3}    IN    A    $(random_ipv4)"
            echo "${ns4}    IN    A    $(random_ipv4)"
            ;;
    esac
}

# Generate A and/or AAAA records
# Args: [name] [show_header]
generate_address_records() {
    local name="${1:-@}"
    local show_header="${2:-1}"
    local choice=$(random_range 1 5)

    if [ "$show_header" -eq 1 ]; then
        echo ""
        echo "; Address records"
    fi

    case $choice in
        1) # A only
            echo "${name}    IN    A    $(random_ipv4)"
            ;;
        2) # AAAA only
            echo "${name}    IN    AAAA    $(random_ipv6)"
            ;;
        3) # Both A and AAAA
            echo "${name}    IN    A    $(random_ipv4)"
            echo "${name}    IN    AAAA    $(random_ipv6)"
            ;;
        4) # Two A records
            echo "${name}    IN    A    $(random_ipv4)"
            echo "${name}    IN    A    $(random_ipv4)"
            ;;
        5) # Two AAAA records
            echo "${name}    IN    AAAA    $(random_ipv6)"
            echo "${name}    IN    AAAA    $(random_ipv6)"
            ;;
    esac
}

# Randomly generate TXT records
# Args: [name] [chance_percent] [max_count] [show_header]
generate_txt_records() {
    local name="${1:-@}"
    local chance_percent="${2:-50}"
    local max_count="${3:-4}"
    local show_header="${4:-1}"

    local roll=$(random_range 1 100)
    if [ $roll -le $chance_percent ]; then
        local count=$(random_range 1 $max_count)

        if [ "$show_header" -eq 1 ]; then
            echo ""
            echo "; TXT records"
        fi

        for i in $(seq 1 $count); do
            local txt_type=$(random_range 1 8)
            local txt=""

            case $txt_type in
                1) txt="v=spf1 include:_spf.google.com ~all" ;;
                2) txt="v=spf1 ip4:$(random_ipv4)/24 -all" ;;
                3) txt="google-site-verification=$(random_string 32)" ;;
                4) txt="MS=$(random_string 16)" ;;
                5) txt="facebook-domain-verification=$(random_string 22)" ;;
                6) txt="apple-domain-verification=$(random_string 16)" ;;
                7) txt="_dmarc.v=DMARC1; p=reject; rua=mailto:dmarc@$(random_string 8).com" ;;
                8) txt="$(random_string $(random_range 10 50))" ;;
            esac

            echo "${name}    IN    TXT    \"${txt}\""
        done
    fi
}

# Randomly generate MX records
# Args: domain [name] [chance_percent] [show_header]
generate_mx_records() {
    local domain=$1
    local name="${2:-@}"
    local chance_percent="${3:-100}"
    local show_header="${4:-1}"

    local roll=$(random_range 1 100)
    if [ $roll -le $chance_percent ]; then
        local count=$(random_range 1 3)

        if [ "$show_header" -eq 1 ]; then
            echo ""
            echo "; Mail exchangers"
        fi

        local mx_hosts=("mail" "mx" "smtp" "mailhost" "mx1" "mx2" "mx3" "aspmx")
        local providers=("" ".l.google.com" ".protection.outlook.com" ".mailgun.org")

        for i in $(seq 1 $count); do
            local priority=$((i * 10))
            local use_provider=$(random_range 0 1)

            if [ $use_provider -eq 1 ] && [ $i -eq 1 ]; then
                local provider=${providers[$(random_range 1 $((${#providers[@]} - 1)))]}
                local mx_host=${mx_hosts[$(random_range 0 $((${#mx_hosts[@]} - 1)))]}
                echo "${name}    IN    MX    ${priority}    ${mx_host}${provider}."
            else
                local mx_host=${mx_hosts[$(random_range 0 $((${#mx_hosts[@]} - 1)))]}
                echo "${name}    IN    MX    ${priority}    ${mx_host}.${domain}."
            fi
        done
    fi
}

# Randomly generate SRV records
# Args: domain [name] [chance_percent] [show_header]
generate_srv_records() {
    local domain=$1
    local name="${2:-@}"
    local chance_percent="${3:-15}"
    local show_header="${4:-1}"

    local roll=$(random_range 1 100)
    if [ $roll -le $chance_percent ]; then
        local count=$(random_range 1 3)

        if [ "$show_header" -eq 1 ]; then
            echo ""
            echo "; SRV records"
        fi

        # Common SRV service definitions: service proto target_prefix
        local services=(
            "_sip._tcp sip"
            "_sip._udp sip"
            "_xmpp-client._tcp xmpp"
            "_xmpp-server._tcp xmpp"
            "_ldap._tcp ldap"
            "_kerberos._tcp kerberos"
            "_kerberos._udp kerberos"
            "_http._tcp www"
            "_https._tcp www"
            "_minecraft._tcp mc"
            "_ts3._udp ts3"
            "_autodiscover._tcp autodiscover"
            "_caldav._tcp caldav"
            "_carddav._tcp carddav"
            "_imap._tcp imap"
            "_imaps._tcp imap"
            "_submission._tcp smtp"
        )

        local used_services=()
        for i in $(seq 1 $count); do
            # Pick a unique service
            local service_idx
            local service_def
            local attempts=0
            while true; do
                service_idx=$(random_range 0 $((${#services[@]} - 1)))
                service_def="${services[$service_idx]}"
                local is_unique=1
                for used in "${used_services[@]}"; do
                    if [ "$used" == "$service_def" ]; then
                        is_unique=0
                        break
                    fi
                done
                if [ $is_unique -eq 1 ] || [ $attempts -gt 10 ]; then
                    used_services+=("$service_def")
                    break
                fi
                ((attempts++))
            done

            local srv_service=$(echo "$service_def" | cut -d' ' -f1)
            local target_prefix=$(echo "$service_def" | cut -d' ' -f2)

            local priority=$(random_range 0 10)
            local weight=$(random_range 1 100)
            local port=$(random_range 1 65535)

            if [ "$name" == "@" ]; then
                echo "${srv_service}    IN    SRV    ${priority} ${weight} ${port}    ${target_prefix}.${domain}."
            else
                echo "${srv_service}.${name}    IN    SRV    ${priority} ${weight} ${port}    ${target_prefix}.${name}.${domain}."
            fi
        done
    fi
}

# Randomly generate CAA records (apex only)
# Args: domain [chance_percent]
generate_caa_records() {
    local domain=$1
    local chance_percent="${2:-30}"

    local roll=$(random_range 1 100)
    if [ $roll -le $chance_percent ]; then
        echo ""
        echo "; CAA records"

        # Certificate authorities
        local cas=(
            "letsencrypt.org"
            "digicert.com"
            "sectigo.com"
            "godaddy.com"
            "amazon.com"
            "globalsign.com"
            "entrust.net"
            "comodoca.com"
        )

        # Always add 1-8 issue records
        local issue_count=$(random_range 1 8)
        for i in $(seq 1 $issue_count); do
            local ca=${cas[$(random_range 0 $((${#cas[@]} - 1)))]}
            echo "@    IN    CAA    0 issue \"${ca}\""
        done

        # 50% chance to add 1-4 issuewild records
        if [ $(random_range 0 1) -eq 1 ]; then
            local issuewild_count=$(random_range 1 4)
            for i in $(seq 1 $issuewild_count); do
                local ca=${cas[$(random_range 0 $((${#cas[@]} - 1)))]}
                echo "@    IN    CAA    0 issuewild \"${ca}\""
            done
        fi

        # 30% chance to add iodef (incident reporting)
        if [ $(random_range 1 100) -le 30 ]; then
            local iodef_type=$(random_range 1 2)
            if [ $iodef_type -eq 1 ]; then
                echo "@    IN    CAA    0 iodef \"mailto:security@${domain}\""
            else
                echo "@    IN    CAA    0 iodef \"https://${domain}/caa-report\""
            fi
        fi
    fi
}

# Generate random subdomain name
random_subdomain_name() {
    local names=("www" "mail" "ftp" "api" "app" "dev" "staging" "test" "beta" "admin" "portal" "cdn" "static" "assets" "img" "images" "files" "download" "upload" "blog" "shop" "store" "support" "help" "docs" "wiki" "forum" "auth" "login" "dashboard" "panel" "manage" "secure" "vpn" "remote" "cloud" "backup" "db" "mysql" "postgres" "redis" "mongo" "elastic" "kafka" "rabbit" "git" "ci" "jenkins" "grafana" "prometheus" "logs" "metrics")
    local choice=$(random_range 0 1)

    if [ $choice -eq 0 ]; then
        echo "${names[$(random_range 0 $((${#names[@]} - 1)))]}"
    else
        echo "$(random_string $(random_range 3 8))"
    fi
}

# Generate NS records for subdomain (15% chance)
generate_subdomain_ns() {
    local subdomain=$1
    local domain=$2
    local chance=$(random_range 1 100)

    if [ $chance -le 15 ]; then
        local ns_count=$(random_range 1 2)
        for i in $(seq 1 $ns_count); do
            echo "${subdomain}    IN    NS    ns${i}.${subdomain}.${domain}."
        done
    fi
}

# Generate subdomains (0-4)
generate_subdomains() {
    local domain=$1
    local count=$(random_range 0 4)

    if [ $count -gt 0 ]; then
        echo ""
        echo "; Subdomains"

        local used_names=()
        for i in $(seq 1 $count); do
            local subdomain=""
            # Generate unique subdomain name
            while true; do
                subdomain=$(random_subdomain_name)
                local is_unique=1
                for used in "${used_names[@]}"; do
                    if [ "$used" == "$subdomain" ]; then
                        is_unique=0
                        break
                    fi
                done
                if [ $is_unique -eq 1 ]; then
                    used_names+=("$subdomain")
                    break
                fi
            done

            echo ""
            echo "; ${subdomain}.${domain}"
            generate_address_records "$subdomain" 0
            generate_subdomain_ns "$subdomain" "$domain"
            generate_txt_records "$subdomain" 50 2 0
            generate_mx_records "$domain" "$subdomain" 15 0
            generate_srv_records "$domain" "$subdomain" 15 0
        done
    fi
}

# Generate complete zone file
generate_zone() {
    local domain=$1
    local output_file="${OUTPUT_DIR}/${domain}.zone"

    {
        generate_soa "$domain"
        generate_ns_records "$domain"
        generate_address_records "@" 1
        generate_txt_records "@" 50 4 1
        generate_mx_records "$domain" "@" 100 1
        generate_srv_records "$domain" "@" 20 1
        generate_caa_records "$domain" 50
        generate_subdomains "$domain"
    } > "$output_file"

    echo "Generated: $output_file"
}

# Main
main() {
    if [ "$1" == "--random" ]; then
        local count=${2:-1}
        OUTPUT_DIR="${3:-.}"
        mkdir -p "$OUTPUT_DIR"

        for i in $(seq 1 $count); do
            local domain="$(random_domain)"
            generate_zone "$domain"

            # ensure dediplication in zone
            awk '!seen[$0]++' "$OUTPUT_DIR/${domain}.zone" > "$OUTPUT_DIR/${domain}.zone.nodup"
            mv "$OUTPUT_DIR/${domain}.zone.nodup" "$OUTPUT_DIR/${domain}.zone"

        done
    elif [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
        cat << EOF
Zone File Generator - Generate random BIND format zone files

Usage:
    $(basename $0) [domain] [output_dir]     Generate zone for specific domain
    $(basename $0) --random [count] [dir]    Generate random domains
    $(basename $0) --help                    Show this help

Examples:
    $(basename $0) example.com               Generate example.com.zone in current dir
    $(basename $0) example.com ./zones       Generate in ./zones directory
    $(basename $0) --random 5 ./zones        Generate 5 random zone files

Generated zones include:
    - 1 SOA record (apex)
    - 0, 1, 2, or 4 NS records (apex) with glue A records
    - A and/or AAAA records (apex) - randomly A, AAAA, both, or multiple
    - TXT records (apex) - randomly 0-4 records
    - 0-3 MX records (apex) - random count
    - SRV records (apex) - 20% chance, 1-3 records
    - CAA records (apex) - 50% chance, issue/issuewild/iodef
    - 0-4 subdomains, each with:
        - A/AAAA records (random combination)
        - NS records (15% chance)
        - TXT records (50% chance)
        - MX records (15% chance, 1-3 records)
        - SRV records (15% chance, 1-3 records)
EOF
        exit 0
    else
        OUTPUT_DIR="${2:-.}"
        mkdir -p "$OUTPUT_DIR"
        generate_zone "$DOMAIN"
    fi
}

main "$@"
